name: Performance Audit
on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit Website Performance
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: 'https://694e2633d57c3cbb131fb357--tourmaline-croquembouche-7a448b.netlify.app' 
          uploadArtifacts: true 
          temporaryPublicStorage: true